### ISSUE TITLE
Add "profileId" validation checks on public APIs

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/bedrock-web-profile-manager#25]
We should be checking for `profileId && typeof profileId === 'string'` (note that some places that do checks at all aren't checking for `profileId` truthiness, i.e., not an empty string).

**Comment by aljones15** [comment]
ok I'll get on this tomorrow provided nothing else is super pressing. Good issue BTW. Should we be checking just here or also in bedrock-profile-http? Are there any validators?

**Comment by dlongley** [comment]
Sure, at the end of the day, we should be checking in all the places and adding validators where needed. We may need to make further updates to those as we clean up the authority model in the *http libs, but getting checks in place now is a good idea.

**Comment by aljones15** [comment]
Closing this as the checks for this project are in.
