### ISSUE TITLE
Update to edv-client 4.x

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-web-profile-manager#34]
Locate usage of `edvClient.find` and update to the new API that returns `{documents: [...]}`.

The find API is used internally, so adaptations will need to be made there.  This is in the `collection.get` API for instance:

https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/7bcfa68f4524ad77dec1f7b7aba5b0c6c60a454f/Collection.js#L34-L39

Also, there are instances where the results of `find` are just passed up the stack. For instance in the `collection.getAll` API.

https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/7bcfa68f4524ad77dec1f7b7aba5b0c6c60a454f/Collection.js#L41-L46

I think in this latter case we will want to continue passing on the result from the `find` API which would make this a breaking change in bedrock-web-profile-manager.  @dlongley @gannan08 any thoughts on this matter?

**Comment by dlongley** [comment]
I think we want to just return an array from `getAll` ... so wouldn't be a breaking change then. If we had exposed `findDocuments` we'd want to change it so it returned `{documents}`, but it's private, so we should be good.

**Comment by dlongley** [comment]
We'll probably need to remove `getAll()` in the future in favor of just exposing `findDocuments` or something anyway ... but that's not for now.
