### ISSUE TITLE
Implement on demand delegation.

### ISSUE THREAD

**Issue by mandyvenables** [digitalbazaar/bedrock-web-profile-manager#57]
[TODO:](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L480) Implement on demand delegation; if agent has a zcap for using the profile's zcap delegation key, delegate a zcap for reading from the user's EDV.

[TODO:](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L306) once delegate on demand is implemented for agents with that capability, remove this unnecessary delegation.

[TODO:](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L316) once delegate on demand is implemented for agents with that capability, remove this unnecessary delegation.

[TODO:](https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L318) note that `user-edv-kak` will be duplicated here -- future on demand generation of zcaps should try to avoid this

**Comment by dlongley** [comment]
Addressed/made irrelevant by #96.
