### ISSUE TITLE
Can `options.kmsModule` be factored out of ProfileManager API

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-web-profile-manager#77]
https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L44

Formerly, this API also accepted `options.kmsBaseUrl` and that was factored out.  Can `options.kmsModule` be factored out as well?

The only usage for that parameter is here: https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/master/ProfileManager.js#L549-L563

My thought at this point is whether or not the `kmsModule` could be a property of the keystore config.  Would it be good to have all keys in a keystore use the same `kmsModule`?

**Comment by dlongley** [comment]
Addressed by #92.
