### ISSUE TITLE
`getProfiles` fails if unable to get all profiles.

### ISSUE THREAD

**Issue by tolson4** [digitalbazaar/bedrock-web-profile-manager#85]
Currently, if a profile agent does not have the required zcaps to get its associated profile, a call to `getProfiles` will fail even if other profiles have already been retrieved.

https://github.com/digitalbazaar/bedrock-web-profile-manager/blob/d371998227b4d9b6fb029d1de55a8cc375101abe/ProfileManager.js#L524-L528

Ideally this method would still return any profiles that is has already retrieved or can retrieve, and handle the failure internally.

We have been able to reliably reproduce this issue by associating two profiles with a single account. On creation of the second profile, `initializeAccessManagement` is never called. This appears to leave the profile agent for that profile in a state where it does not have the required zcaps to retrieve the profile document. This in turn throws an error when an attempt is made to fetch all the profiles for an account.

**Comment by dlongley** [comment]
Closing since v16 addresses this by always fully provisioning profiles via a recoverable / continuable backend process.
